"""add is_active field to trip

Revision ID: 6e0d5dfb7dd6
Revises: 841c24bbabd7
Create Date: 2024-07-22 13:57:36.282212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6e0d5dfb7dd6"
down_revision: Union[str, None] = "841c24bbabd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trip", sa.Column("is_active", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trip", "is_active")
    # ### end Alembic commands ###
