"""Add field timestamp for message model

Revision ID: 07d4b667e97d
Revises: e78e84cb6a21
Create Date: 2024-08-02 12:39:36.535681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "07d4b667e97d"
down_revision: Union[str, None] = "e78e84cb6a21"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "message", sa.Column("timestamp", sa.TIMESTAMP(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("message", "timestamp")
    # ### end Alembic commands ###
