"""add review model

Revision ID: 9bb9c17ea9a3
Revises: 6e0d5dfb7dd6
Create Date: 2024-07-22 14:53:00.215826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bb9c17ea9a3"
down_revision: Union[str, None] = "6e0d5dfb7dd6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "review",
        sa.Column(
            "review_id", sa.Integer(), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("trip_id", sa.Integer(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(), nullable=True),
        sa.CheckConstraint(
            "score >= 0 AND score <= 5",
            name=op.f("ck_review_check_score_range"),
        ),
        sa.ForeignKeyConstraint(
            ["trip_id"], ["trip.trip_id"], name=op.f("fk_review_trip_id_trip")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.user_id"], name=op.f("fk_review_user_id_user")
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_review")),
    )
    op.create_index(
        op.f("ix_review_review_id"), "review", ["review_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_review_id"), table_name="review")
    op.drop_table("review")
    # ### end Alembic commands ###
