"""reformat available_sits from str to int

Revision ID: 841c24bbabd7
Revises: b5c2f63e3f70
Create Date: 2024-07-20 18:14:28.985461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "841c24bbabd7"
down_revision: Union[str, None] = "b5c2f63e3f70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trip",
        "available_sits",
        existing_type=sa.VARCHAR(),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="available_sits::integer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "trip",
        "available_sits",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
        postgresql_using="available_sits::integer"
    )
    # ### end Alembic commands ###
